/*
File: database_skeleton.sql

Description:
SQL script that creates a database to be populated later.

@author Kyle Krebs

*/

CREATE DATABASE IF NOT EXISTS basketball_stats;

USE basketball_stats;

-- create the play description table
CREATE TABLE playdescriptions (
    PlayID INT PRIMARY KEY AUTO_INCREMENT,
    PlayType VARCHAR(50),
    Direction VARCHAR(50) NULL,
    Play_Action VARCHAR(50) NULL
);

-- create the shot type table
CREATE TABLE shottypes (
    ShotType VARCHAR(50) PRIMARY KEY
); 

-- create the play outcomes table
CREATE Table playoutcomes (
    Outcome VARCHAR(50) PRIMARY KEY
);

-- create the opponents table
CREATE TABLE opponents (
    Opponent VARCHAR(50) PRIMARY KEY
);

-- create the main table that will hold all plays
CREATE TABLE plays (
    PlayID INT,
    ShotType VARCHAR(50),
    Outcome VARCHAR(50),
    Opponent VARCHAR(50),
    FOREIGN KEY (PlayID) REFERENCES PlayDescriptions(PlayID),
    FOREIGN KEY (ShotType) REFERENCES ShotTypes(ShotType),
    FOREIGN KEY (Outcome) REFERENCES PlayOutcomes(Outcome),
    FOREIGN KEY (Opponent) REFERENCES Opponents(Opponent)
);


USE basketball_stats;
CREATE TABLE teamgames (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Team VARCHAR(255),
    Opponent VARCHAR(255),
    Team_Pts INT,
    Opponent_Pts INT,
    TotalPts INT,
    Diff INT,
    O_CutPlays INT,
    O_Cut2PA INT,
    O_Cut2PM INT,
    O_Cut2P FLOAT,
    O_CutTO INT,
    O_CutFouls INT,
    O_PnrPlays INT,
    O_Pnr3PA INT,
    O_Pnr3PM INT,
    O_Pnr3P FLOAT,
    O_Pnr2PA INT,
    O_Pnr2PM INT,
    O_Pnr2P FLOAT,
    O_PnrMiA INT,
    O_PnrMiM INT,
    O_PnrMi FLOAT,
    O_PnrEFG FLOAT,
    O_PnrTO INT,
    O_PnrFouls INT,
    O_PostPlays INT,
    O_Post2PA INT,
    O_Post2PM INT,
    O_Post2P FLOAT,
    O_PostTO INT,
    O_PostFouls INT,
    O_RollPlays INT,
    O_Roll3PA INT,
    O_Roll3PM INT,
    O_Roll3P FLOAT,
    O_Roll2PA INT,
    O_Roll2PM INT,
    O_Roll2P FLOAT,
    O_RollMiA INT,
    O_RollMiM INT,
    O_RollMi FLOAT,
    O_RollEFG FLOAT,
    O_RollTO INT,
    O_RollFouls INT,
    O_SUShotPlays INT,
    O_SUShot3PA INT,
    O_SUShot3PM INT,
    O_SUShot3P FLOAT,
    O_SUShotMiA INT,
    O_SUShotMiM INT,
    O_SUShotMi FLOAT,
    O_SUShotTO INT,
    O_SUShotFouls INT,
    O_SUDrivePlays INT,
    O_SUDriveMiA INT,
    O_SUDriveMiM INT,
    O_SUDriveMi FLOAT,
    O_SUDrive2PA INT,
    O_SUDrive2PM INT,
    O_SUDrive2P FLOAT,
    O_SUDriveTO INT,
    O_SUDriveFouls INT,
    O_IsoPlays INT,
    O_Iso3PA INT,
    O_Iso3PM INT,
    O_Iso3P FLOAT,
    O_Iso2PA INT,
    O_Iso2PM INT,
    O_Iso2P FLOAT,
    O_IsoMiA INT,
    O_IsoMiM INT,
    O_IsoMi FLOAT,
    O_IsoEFG FLOAT,
    O_IsoTO INT,
    O_IsoFouls INT,
    O_TransitionPlays INT,
    O_Transition3PA INT,
    O_Transition3PM INT,
    O_Transition3P FLOAT,
    O_Transition2PA INT,
    O_Transition2PM INT,
    O_Transition2P FLOAT,
    O_TransitionMiA INT,
    O_TransitionMiM INT,
    O_TransitionMi FLOAT,
    O_TransitionEFG FLOAT,
    O_TransitionTO INT,
    O_TransitionFouls INT,
    O_OfscPlays INT,
    O_Ofsc3PA INT,
    O_Ofsc3PM INT,
    O_Ofsc3P FLOAT,
    O_Ofsc2PA INT,
    O_Ofsc2PM INT,
    O_Ofsc2P FLOAT,
    O_OfscMiA INT,
    O_OfscMiM INT,
    O_OfscMi FLOAT,
    O_OfscEFG FLOAT,
    O_OfscTO INT,
    O_OfscFouls INT,
    O_HaOfPlays INT,
    O_HaOf3PA INT,
    O_HaOf3PM INT,
    O_HaOf3P FLOAT,
    O_HaOf2PA INT,
    O_HaOf2PM INT,
    O_HaOf2P FLOAT,
    O_HaOfMiA INT,
    O_HaOfMiM INT,
    O_HaOfMi FLOAT,
    O_HaOfEFG FLOAT,
    O_HaOfTO INT,
    O_HaOfFouls INT,
    D_CutPlays INT,
    D_Cut2PA INT,
    D_Cut2PM INT,
    D_Cut2P FLOAT,
    D_CutTO INT,
    D_CutFouls INT,
    D_PnrPlays INT,
    D_Pnr3PA INT,
    D_Pnr3PM INT,
    D_Pnr3P FLOAT,
    D_Pnr2PA INT,
    D_Pnr2PM INT,
    D_Pnr2P FLOAT,
    D_PnrMiA INT,
    D_PnrMiM INT,
    D_PnrMi FLOAT,
    D_PnrEFG FLOAT,
    D_PnrTO INT,
    D_PnrFouls INT,
    D_PostPlays INT,
    D_Post2PA INT,
    D_Post2PM INT,
    D_Post2P FLOAT,
    D_PostTO INT,
    D_PostFouls INT,
    D_RollPlays INT,
    D_Roll3PA INT,
    D_Roll3PM INT,
    D_Roll3P FLOAT,
    D_Roll2PA INT,
    D_Roll2PM INT,
    D_Roll2P FLOAT,
    D_RollMiA INT,
    D_RollMiM INT,
    D_RollMi FLOAT,
    D_RollEFG FLOAT,
    D_RollTO INT,
    D_RollFouls INT,
    D_SUShotPlays INT,
    D_SUShot3PA INT,
    D_SUShot3PM INT,
    D_SUShot3P FLOAT,
    D_SUShotMiA INT,
    D_SUShotMiM INT,
    D_SUShotMi FLOAT,
    D_SUShotTO INT,
    D_SUShotFouls INT,
    D_SUDrivePlays INT,
    D_SUDriveMiA INT,
    D_SUDriveMiM INT,
    D_SUDriveMi FLOAT,
    D_SUDrive2PA INT,
    D_SUDrive2PM INT,
    D_SUDrive2P FLOAT,
    D_SUDriveTO INT,
    D_SUDriveFouls INT,
    D_IsoPlays INT,
    D_Iso3PA INT,
    D_Iso3PM INT,
    D_Iso3P FLOAT,
    D_Iso2PA INT,
    D_Iso2PM INT,
    D_Iso2P FLOAT,
    D_IsoMiA INT,
    D_IsoMiM INT,
    D_IsoMi FLOAT,
    D_IsoEFG FLOAT,
    D_IsoTO INT,
    D_IsoFouls INT,
    D_TransitionPlays INT,
    D_Transition3PA INT,
    D_Transition3PM INT,
    D_Transition3P FLOAT,
    D_Transition2PA INT,
    D_Transition2PM INT,
    D_Transition2P FLOAT,
    D_TransitionMiA INT,
    D_TransitionMiM INT,
    D_TransitionMi FLOAT,
    D_TransitionEFG FLOAT,
    D_TransitionTO INT,
    D_TransitionFouls INT,
    D_OfscPlays INT,
    D_Ofsc3PA INT,
    D_Ofsc3PM INT,
    D_Ofsc3P FLOAT,
    D_Ofsc2PA INT,
    D_Ofsc2PM INT,
    D_Ofsc2P FLOAT,
    D_OfscMiA INT,
    D_OfscMiM INT,
    D_OfscMi FLOAT,
    D_OfscEFG FLOAT,
    D_OfscTO INT,
    D_OfscFouls INT,
    D_HaOfPlays INT,
    D_HaOf3PA INT,
    D_HaOf3PM INT,
    D_HaOf3P FLOAT,
    D_HaOf2PA INT,
    D_HaOf2PM INT,
    D_HaOf2P FLOAT,
    D_HaOfMiA INT,
    D_HaOfMiM INT,
    D_HaOfMi FLOAT,
    D_HaOfEFG FLOAT,
    D_HaOfTO INT,
    D_HaOfFouls INT
);

-- Add the SecondaryPlayID column to the plays table
ALTER TABLE plays
ADD COLUMN SecondaryPlayID;

-- Add the foreign key constraint for the SecondaryPlayID column
ALTER TABLE plays
ADD CONSTRAINT fk_SecondaryPlayID
FOREIGN KEY (SecondaryPlayID) REFERENCES PlayDescriptions(PlayID);

